const materials = [
	"aluminium",
	"chromium",
	"copper",
	"gold",
	"iron",
	"lead",
	"nickel",
	"platinum",
	"silver",
	"tin",
	"titanium",
	"zinc",
	"steel",
	"brass",
	"electrum",
	"bronze",
	"sterling",
	"pewter",
	"adobe",
	"bamboo",
	"cordwood",
	"paper",
	"dirt",
	"rock",
	"sawdust",
	"straw",
	"thatch",
	"alabaster",
	"granite",
	"clay",
	"porcelain",
	"concrete",
	"gel",
	"glass",
	"granite",
	"latex",
	"limestone",
	"copper",
	"marble",
	"papier-mâché",
	"plaster",
	"salt",
	"rubber",
	"soapstone",
	"stone",
	"terracotta",
	"marble",
	"wax",
	"steel"
];

const items = [
	"tome",
	"scroll",
	"tablet",
	"torch",
	"lamp",
	"flashlight",
	"matches",
	"beacon",
	"bell",
	"staff",
	"stick",
	"cane",
	"pole",
	"knife",
	"blade",
	"sword",
	"axe",
	"bean",
	"seed",
	"cloak",
	"hood",
	"mask",
	"robe",
	"compass",
	"guide",
	"map"
];

const herbs = [
	"agrimony",
	"alder buckthorne",
	"aloe",
	"aniseed",
	"artichoke",
	"bilberry",
	"black cohosh",
	"blackcurrant",
	"black mustard seed",
	"brahmi",
	"burdock",
	"caraway",
	"celery",
	"centaury",
	"chamomile",
	"chaste tree",
	"cherry",
	"chickweed",
	"chicory",
	"chili",
	"cinquefoil",
	"cleavers",
	"cranberry",
	"cucumber",
	"daisy",
	"dandelion",
	"dill",
	"echinacea",
	"elderberry",
	"elderflower",
	"eucalyptus",
	"evening primrose",
	"eyebright",
	"fennel",
	"fennugreek",
	"feverfew",
	"fig",
	"fleabane",
	"garlic",
	"ginger",
	"ginko",
	"goji berries",
	"gotu kola",
	"honeysuckle",
	"hops",
	"horse chestnut",
	"horseradish",
	"juniper",
	"kiwifruit",
	"ladymantle",
	"lavender",
	"lemon",
	"lemon balm",
	"licorice",
	"lime",
	"linden",
	"marigold",
	"cannabis",
	"meadowsweet",
	"milk thistle",
	"motherwort",
	"mugwort",
	"mullein",
	"neem",
	"nettle",
	"nutmeg",
	"papaya",
	"parsley",
	"passionflower",
	"pine",
	"plantain",
	"psyllium",
	"purslane",
	"red clover",
	"red raspberry",
	"rose geranium",
	"rosehips",
	"rosemary",
	"sage",
	"skullcap",
	"slippery elm",
	"spruce",
	"wort",
	"tea tree oil",
	"thuja",
	"tumeric",
	"thyme",
	"tulsi",
	"uva-ursi",
	"valerian",
	"vervain",
	"viola",
	"watercress",
	"wheatgrass",
	"willow bark",
	"witch hazel"
];

const plants = [
	"amaryllis",
	"begonia",
	"spider lily",
	"bird of paradise",
	"busy lizzie",
	"aluminum plant",
	"arrowhead",
	"boston fern",
	"date palm",
	"evergreen",
	"aloe vera",
	"rubber plant",
	"century plant",
	"christmas cheer",
	"donkeys tail",
	"bromeliad",
	"ficus",
	"calathea",
	"orchid",
	"cactus",
	"coral bead",
	"fern",
	"calla lily",
	"belladonna",
	"daisy"
];

const liquids = [
	"water",
	"blood",
	"juice",
	"vinegar",
	"mayonnaise",
	"paste",
	"ethanol",
	"liqueur",
	"wine",
	"mercury",
	"acid",
	"paint",
	"milk",
	"oil",
	"sweat",
	"honey",
	"coffee",
	"tea",
	"bromine"
];

const scents = 
[
'pine','citrus','beach','cinnamon','lavender','vanilla','pumpkin','peppermint','jasmine','apple','olive oil','oatmeal','tobacco','eucalyptus','cotton','sage','cocoa butter','shea','espresso','fir','cedarwood','peppermint','coconut','castor oil','cocoa butter','avocado','almond oil','palm oil','patchouli'
]

const artifacts = 
[
'cape','cowl','sash','cloak','wings','boots','sandals','helm','crown','helmet','hat','shield','buckler','charm','talisman','orb','tome','sphere','bird','emblem','clover','ladybird','cards','hourglass','glyph','crest','badge','spirit','spyglass','bow','bowstring','vial','purse','cart','curnucopia','statue','mask','runes','figurine','horn','pendant','collar','amulet','garniture','necklace','ake','club','blade','trident','ring','eye','seal','breastplate','tunic','scales','armor','plate','stone','chess pieces','pottery','stelae','tablet','drum','disc','calendar','inscription','pot','utu','shoe','brooch','pebble','chest','bust','cup','relief','glass','seal'
]
